
#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 2) buffer Digits {
    uint[] data;
} digits;

layout(push_constant) uniform PushConstants {
    uint particle_count;
    uint index;
    uint value;
} pc;

void main() {
    uint id = gl_GlobalInvocationID.x;

    if (id >= pc.particle_count) {
        return;
    }

    digits.data[id] = ((digits.data[id] >> pc.index) & 1u) == pc.value ? 1 : 0;
}

